channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=24.1.2
- pip:
  - mlflow==2.15.1
  - pandas==2.1.4
  - pathlib==1.0.1
  - psutil==5.9.5
  - scikit-learn==1.3.2
  - xgboost==2.1.1
name: mlflow-env
